# -*- coding: utf-8 -*-
"""encryption_using_transformers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LTJRztvUuKclV7VfjsbvKAMXVorjIgHc
"""

!pip install transformers
!pip install datasets
!pip install cryptography

import pandas as pd
import datasets
from pprint import pprint
from transformers import AutoTokenizer
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend
import os
import hashlib

def text_to_key(text):
    return hashlib.sha256(text.encode()).digest()
# Example Usage
text = input()
key = text_to_key(text)
print(key)

text_w = input()

def whole_setup(key,text_w):
  #encrypt
  def encrypt(plain_text, key):
     # Generate a random 96-bit IV.
      iv = os.urandom(12)
     # Create AES-GCM Cipher.
      cipher = Cipher(algorithms.AES(key), modes.GCM(iv), backend=default_backend())
      encryptor = cipher.encryptor()
      # Encrypt the data.
      cipher_text = encryptor.update(plain_text.encode()) + encryptor.finalize()
     # Return IV, authentication tag (needed for decryption) and cipher_text.
      return iv, encryptor.tag, cipher_text

  #decrypt
  def decrypt(iv, tag, cipher_text, key):
      cipher = Cipher(algorithms.AES(key), modes.GCM(iv, tag), backend=default_backend())
      decryptor = cipher.decryptor()
      return decryptor.update(cipher_text) + decryptor.finalize()


  tokenizer = AutoTokenizer.from_pretrained("EleutherAI/pythia-70m")
  encoded_text = tokenizer(text_w)["input_ids"]
  encoded_list = encoded_text
  encoded_str = ','.join(map(str, encoded_list))
  large_text = encoded_str
  iv, tag, encrypted_data = encrypt(large_text, key)
  decrypt_dext_ = decrypt(iv, tag, encrypted_data, key)
  decrypt_text = decrypt_dext_.decode()
  decoded_list= decrypt_text.split(',')
  decoded_list_int = list(map(int, decoded_list))
  decoded_text = tokenizer.decode(decoded_list_int)
  return {'decrypt_tt':decoded_text}

print('decryption',whole_setup(key,text_w))